sudo: required
language: bash
services:
  - docker
before_install:
  #- docker build -t chaste:dependencies https://github.com/bdevans/chaste-docker.git
  - docker build -t chaste:2017.1 --build-arg TAG=2017.1 https://github.com/bdevans/chaste-docker.git#volume
  - docker run -it -v chaste_data:/home/chaste -v $(pwd):/home/chaste/src/projects chaste:2017.1
script:
  - docker ps -a
  #- ./build_images.sh
  #- ./build_chaste.sh
  - ./test.sh
