sudo: required
language: bash
services:
  - docker
before_install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "REPO=$TRAVIS_REPO_SLUG, TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  # TODO on push: docker build --target base -t chaste/base https://github.com/$TRAVIS_REPO_SLUG.git#$BRANCH
  # docker push chaste/base
  # --build-arg TAG=release_2019.1
  # Trigger: docker run -it -d --init --name chaste chaste/base "build_chaste.sh release_2019.1; tesh.sh"
  # docker exec -it chaste sh -c "build_chaste.sh release_2019.1"
  # docker exec -it chaste test.sh
  - docker build -t chaste --build-arg TAG=- https://github.com/$TRAVIS_REPO_SLUG.git#$BRANCH
  - docker run -it -d -v chaste_data:/home/chaste -v $(pwd):/home/chaste/src/projects chaste
script:
  - docker ps -a
  - docker images
  - docker inspect chaste
  - docker volume inspect chaste_data
  # - ./build_images.sh
  # - docker run -it -v chaste_data:/home/chaste chaste:2017.1 ./build_chaste.sh
  # - docker run -it -v chaste_data:/home/chaste chaste:2017.1 "./test.sh"
