sudo: required
language: bash
services:
  - docker
before_install:
  #- docker build -t chaste:dependencies https://github.com/bdevans/chaste-docker.git
  - docker build -t chaste --build-arg TAG=- https://github.com/bdevans/chaste-docker.git
  - docker run -it -d -v chaste_data:/home/chaste -v $(pwd):/home/chaste/src/projects chaste  #- docker run -it -v chaste_data::/home/chaste -v $(pwd):/home/chaste/projects chaste
script:
  - docker ps -a
  - docker images
  - docker inspect chaste
  - docker volume inspect chaste_data
  #- ./build_images.sh
  #- docker run -it -v chaste_data:/home/chaste chaste:2017.1 ./build_chaste.sh
  #- docker run -it -v chaste_data:/home/chaste chaste:2017.1 "./test.sh"
