# docker run -it -v $(pwd):/usr/chaste/src/projects chaste:$VER

FROM chaste:dependencies
MAINTAINER Ben Evans <ben.d.evans@gmail.com>

ARG CHASTE_VERSION=3.4.93221
ENV VER=$CHASTE_VERSION
ARG NCORES=4
# Persist environment variable for project builds
ENV NCORES=$NCORES

#USER chaste
RUN echo "Building Chaste ${VER}"
#RUN git clone -b $VER https://github.com/Chaste/Chaste.git src

RUN mkdir -p build
#WORKDIR /usr/chaste/build
#RUN cmake -DCMAKE_BUILD_TYPE:STRING=Release \
#          -DChaste_ERROR_ON_WARNING:BOOL=OFF \
#          -DChaste_UPDATE_PROVENANCE:BOOL=OFF \
#          /usr/chaste/src && \
#    make -j$NCORES

RUN git clone --bare https://github.com/Chaste/template_project.git /usr/chaste/src/projects/template_project
COPY new_project.sh /usr/chaste/

#RUN useradd -ms /bin/bash chaste
#RUN chown chaste:chaste -R /usr/chaste
RUN chown 1000:1000 -R /usr/chaste
# Hook to link to host chaste source folder, and set it as the working dir
# New method for automatically mounting volumes
# N.B. Changing the volume from within the Dockerfile: If any build steps change the data within the volume after it has been declared, those changes will be discarded.
VOLUME /usr/chaste
