name: Build chaste/base

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      meta-images: chaste/base
      meta-flavor: latest=true
      meta-tags: |
        type=schedule,pattern={{date 'YYYYMMDD'}}
        # type=ref,event=branch
        # type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        # Update the following line to match the base ubuntu image
        type=raw,value=resolute
        type=sha
      labels: |
        org.opencontainers.image.title=Chaste Base Image
        org.opencontainers.image.description=Docker Base Image for Chaste: Cancer, Heart and Soft Tissue Environment
        org.opencontainers.image.url=https://hub.docker.com/repository/docker/chaste/base/general
        org.opencontainers.image.source=https://github.com/Chaste/chaste-docker
      context: .
      platforms: linux/amd64,linux/arm64
      output: image
      target: base
      push: true
      distribute: true
      sign: auto
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
