name: Docker Multi-Arch Base Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-qemu-action
      with:
        platforms: 'amd64,arm64'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      # https://github.com/docker/setup-buildx-action
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: 'amd64,arm64'
        push: true
        tags: chaste/base:test
